# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install dependencies needed
        run: mvn install:install-file -Dfile=/path/to/file.[jar | war] -DgroupId=groupId -DartifactId=artifactId -Dversion=version -Dpackaging=[jar | war]

      - name: Build with Maven
        run: mvn -B -DskipITs=false verify --file pom.xml
